#!/bin/sh

set -e

STAGED_FILES=$(git diff --name-only --cached)

echo 'Formatting...'
npm run format

echo 'Linter Fix...'
npm run lint:fix

echo 'Git add...'
echo "$STAGED_FILES" | while read file; do
    if [ -f "$file" ]; then
        git add "$file"
    fi
done

echo 'Linter...'
npm run lint

echo 'Successfull!'