#!/bin/sh

set -e

STAGED_FILES=$(git diff --name-only --cached)

echo 'Formatting...'
npm run format

echo 'Linter Fix...'
npm run lint:fix

echo 'Update patch version...'
npm run patch:up

echo 'Git add...'
echo "$STAGED_FILES" | xargs git add

echo 'Linter...'
npm run lint

echo 'Successfull!'